name: Build and Test iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app
        xcodebuild -version
        xcrun simctl list devices --json
        
    - name: Grant execute permission for Gradle
      run: chmod +x gradlew
        
    - name: Build Shared Module for iOS
      run: ./gradlew :shared:compileKotlinIosX64
      
    - name: List available simulators (for debugging)
      run: xcrun simctl list devices | grep -E "(iPhone|iPad)" | head -20
      
    - name: Build iOS App for Simulator (Fixed)
      run: |
        cd iosApp
        # Use a more specific destination that exists
        xcodebuild build \
          -scheme iosApp \
          -configuration Debug \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
          -derivedDataPath DerivedData \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Alternative build approach (if above fails)
      run: |
        cd iosApp
        # Simpler approach without specific device
        xcodebuild build \
          -scheme iosApp \
          -configuration Debug \
          -sdk iphonesimulator \
          -derivedDataPath DerivedData \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run iOS Tests
      run: ./gradlew :shared:iosTest
      
    - name: Verify Build Output
      run: |
        if [ -d "iosApp/DerivedData/Build/Products/Debug-iphonesimulator" ]; then
          echo "✅ Build successful! Contents:"
          ls -la iosApp/DerivedData/Build/Products/Debug-iphonesimulator/
        else
          echo "❌ Build directory not found"
          ls -la iosApp/DerivedData/Build/Products/ || true
        fi